### PR TITLE
Support for Digilent Nexys A7 board + UART printf + Runtime C function

### PR DESCRIPTION
**Pull request by kuoyaoming93**
Add support for Nexys A7 board. 

1. Contrain file added (.xdc) 
2. Makefile including the part name of Nexys A7
3. The default configuration of Vicuna demo is too big for Nexys A7. That's why a smaller default config is introduced, and gen_demo.tcl is modified when Nexys A7 is selected
4. Fix: [Add CV32E40X's LSU response filter to sim_vivado TCL](https://github.com/kuoyaoming93/vicuna/commit/892bfeee14a2049e7fc01bfad100f1d77433e0f8)
5. UART printf function
6. Runtime C function (extract clock cycles from RISC-V CSR)

Feel free to add these little changes if you think it's necessary.

Reports for: VREG_W =128, VMEM_W = 32, VMUL_W = 64, VALU_W = 64, VSLD_W = 64

Logic Utilization
Captura de pantalla de 2022-05-30 23-23-38

Timing
Captura de pantalla de 2022-05-30 23-22-51
Captura de pantalla de 2022-05-30 23-22-39

Board
WhatsApp Image 2022-05-30 at 11 41 16 PM

Test.c output
Captura de pantalla de 2022-05-30 21-38-18

### CODE REVIEW

**Comment by kuoyaoming93** [comment]
Add UART printf support.

C code example:

```c
#include <stdint.h>
#include <uart.h>

#define q_field 16

int16_t wires[q_field][q_field] = {
    {0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15},
    {1,0,5,9,15,2,11,14,10,3,8,6,13,12,7,4},
    {2,5,0,6,10,1,3,12,15,11,4,9,7,14,13,8},
    {3,9,6,0,7,11,2,4,13,1,12,5,10,8,15,14},
    {4,15,10,7,0,8,12,3,5,14,2,13,6,11,9,1},
    {5,2,1,11,8,0,9,13,4,6,15,3,14,7,12,10},
    {6,11,3,2,12,9,0,10,14,5,7,1,4,15,8,13},
    {7,14,12,4,3,13,10,0,11,15,6,8,2,5,1,9},
    {8,10,15,13,5,4,14,11,0,12,1,7,9,3,6,2},
    {9,3,11,1,14,6,5,15,12,0,13,2,8,10,4,7},
    {10,8,4,12,2,15,7,6,1,13,0,14,3,9,11,5},
    {11,6,9,5,13,3,1,8,7,2,14,0,15,4,10,12},
    {12,13,7,10,6,14,4,2,9,8,3,15,0,1,5,11},
    {13,12,14,8,11,7,15,5,3,10,9,4,1,0,2,6},
    {14,7,13,15,9,12,8,1,6,4,11,10,5,2,0,3},
    {15,4,8,14,1,10,13,9,2,7,5,12,11,6,3,0}
};

int main(void) {

    uart_puts("Hello world!\n\r");

    int i;
    uint32_t block_size_p;
    // Set the vector configuration
    asm volatile("vsetvli %0, %1, e16, m2, ta, ma" : "=r"(block_size_p) : "r"(q_field));

    uint16_t result[q_field];

    asm volatile("vle16.v v0, (%0);" ::"r"(&wires[0][0])); 
    asm volatile("vle16.v v2, (%0);" ::"r"(&wires[1][0])); 

    asm volatile("vadd.vv v4, v0, v2;");

    asm volatile("vse16.v v4, (%0);" ::"r"(&result[0]));

    uart_printf("A: ");
    for(i=0;i<q_field;i++)
        uart_printf("%d, ", wires[0][i]);
    uart_printf("\n\r");

    uart_printf("B: ");
    for(i=0;i<q_field;i++)
        uart_printf("%d, ", wires[1][i]);
    uart_printf("\n\r");
    
    uart_printf("A+B: ");
    for(i=0;i<q_field;i++)
        uart_printf("%d, ", result[i]);
    uart_printf("\n\r");

    while(1);

    return 0;
}
```

Output:
Captura de pantalla de 2022-05-31 11-18-49

**Comment by kuoyaoming93** [comment]
Add clock cycle support (from risc-v csr).

Example C code:
```c
    long time1,time2;
    time1 = get_mcycle();
    asm volatile("vle16.v v0, (%0);" ::"r"(&wires[0][0])); 
    asm volatile("vle16.v v2, (%0);" ::"r"(&wires[1][0])); 
    asm volatile("vadd.vv v4, v0, v2;");
    asm volatile("vse16.v v4, (%0);" ::"r"(&result[0]));
    time2 = get_mcycle();

    uart_printf("The operation took %d cycles\n\r",time2-time1);
```

Output:
Captura de pantalla de 2022-05-31 11-58-07

**Comment by kuoyaoming93** [comment]
Checks for compatibility
- [ ] Contrain file added (.xdc)
- [ ] Makefile including the part name of Nexys A7
- [ ] Fix: [Add CV32E40X's LSU response filter to sim_vivado TCL](https://github.com/kuoyaoming93/vicuna/commit/892bfeee14a2049e7fc01bfad100f1d77433e0f8)
- [ ] UART printf function, and verilator printf
- [ ] Runtime C function (extract clock cycles from RISC-V CSR)

Regarding smaller top demo is deleted from gen_demo.tcl

**Comment by michael-platzer** [comment]
Hi @kuoyaoming93,

I added some modifications to `verilator_main.cpp` that allow re-using the UART code for printing in Verilator, thus avoiding the code duplication in `uart.c` and `veri_printf.c`. Please have a look at [0286250](https://github.com/vproc/vicuna/commit/0286250a15667a306876a7ea0648262cc7c90054) in branch [kuoyaoming93_main](https://github.com/vproc/vicuna/tree/kuoyaoming93_main).

Printing in Verilator works fine with following test program:
```c
#include <stdint.h>
#include <uart.h>

int main(void)
{
    uart_printf("Hello World!!!\n\n\n");

    asm volatile("jr x0;");
    return 0;
}

```

**Comment by kuoyaoming93** [comment]
Perfect, thanks @michael-platzer! 

I was trying to figure out how to merge those printf since they have basically the same code.
It also works for me. Thank you for all your support.

Captura de pantalla de 2022-06-03 08-00-17

**Comment by kuoyaoming93** [comment]
I just close this PR since you have it in the branch.

**Pull request closed without merging**
